apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: black-rules
  namespace: monitoring
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  groups:
    - name: ssl
      rules:
        - alert: "ssl证书过期警告"
          expr: (probe_ssl_earliest_cert_expiry - time())/86400 < 10
          for: 10s
          labels:
            severity: warn
          annotations:
            description: '域名{{$labels.instance}}的证书还有{{ printf "%.1f" $value }}天就过期了,请尽快更新证书'
            summary: "ssl证书过期警告"
            
