apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dingding-pvc
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: nfs-client
