apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
        app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
        - name: mysql-exporter
          image: prom/mysqld-exporter:latest
          imagePullPolicy: IfNotPresent
          ports:
          - name: mysqlexporter
            containerPort: 9104
            protocol: TCP
          env:
          - name: "DATA_SOURCE_NAME"
            value: thxj:thxj@888@(192.168.1.221:3306)/
          resources:
            requests:
              cpu: 0.2
              memory: 200Mi
            limits:
              cpu: 0.2
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter-svc
  labels:
    app: mysql-exporter-svc
spec:
  ports:
  - port: 9104
    targetPort: 9104
    name: mysqlexporter
  selector:
    app: mysql-exporter
  type: NodePort
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: mysql-exporter-sm
  name: mysql-exporter-sm
spec:
  endpoints:
  - interval: 15s
    port: mysqlexporter
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
  jobLabel: app
  selector:
    matchLabels:
      app: mysql-exporter-svc
